services:
  webapp:
    build: .
    image: crazyrhino/webapp:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017/webapp

  tests:
    image: crazyrhino/webapp:latest
    depends_on:
      - webapp
    command: ["yarn", "test", "test.spec.js"]
    environment:
      - API_URL=http://webapp:3000
volumes:
  mongo-vol:
 