services:
  webapp:
    build: .
    image: crazyrhino/webapp
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGO_URL: mongodb://database:27017/webapp
  database:
    image: mongo:latest
    volumes:
      - mongo-vol:/data/db
volumes:
  mongo-vol:
