services:
  webapp:
    build: .
    image: crazyrhino/webapp:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGO_URL: mongodb://database:27017/webapp
  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/data/db
  tests:
    image: crazyrhino/webapp:latest
    depends_on:
      - webapp
    command: ["yarn", "test", "test.spec.js"]
    environment:
      - API_URL=http://webapp:3000
volumes:
  mongo-vol:
 