---
  name: Build and test
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: Set up Node.js 18
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        
        - name: "Install project dependencies"
          run: yarn install
    
        - name: "Run linting"
          run: yarn lint
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            file: ./dockerfile
            tags: crazyrhino/webapp:latest
        
        - name: Run unit tests
          run: docker-compose up -d

        - name: Run unit tests
          run: docker compose run tests

        - name: Docker Compose down
          run: docker-compose down
  
