---
  name: Build and test
  on:
    push:
      branches:
        - main
  jobs:
    login-to-docker:
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}



    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: Set up Node.js 18
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        
        - name: "Install project dependencies"
          run: yarn install
    
        - name: "Run linting"
          run: yarn lint

        - name: Build Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: crazorhino/webapp:latest